apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-custom-config
data:
  POSTGRES_DB=products
  POSTGRES_USER=productsvcuser
  POSTGRES_PASSWORD=password
#  postgresql: |-
#{{ .Files.get "config/postgresql.conf | indent 4 }}