spring:
  application:
    name: orderservice
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
# This is not needed later in Kubernetes, but only for local development
server:
  port: 8081

management:
  health:
    probes:
      enabled: true

